version: '3'

services:

  discovery-app:
    container_name: discovery-app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8761
    networks:
      - my-network

networks:
  my-network:
    external: true
