version: '3'

services:

  spring-app:
    container_name: discovery-app
    build:
      context: .
      dockerfile: Dockerfile
      image: backend-discovery-app
    ports:
      - 8761
    networks:
      - my-network

networks:
  my-network:
    external: true
