version: '3'

services:

  discovery-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8761
    networks:
      - my-network

networks:
  my-network:
    external: true
