server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://eureka.pickitup.online/eureka
  instance:
    hostname: 43.202.4.152
#    hostname: http://eureka.pickitup.online
---

#spring:
#  config:
#    activate:
#      on-profile: eureka1
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://kubernetes.docker.internal:8763/eureka/
#  instance:
#    hostname: localhost
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: eureka2
#
#server:
#  port: 8763
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#  instance:
#    hostname: kubernetes.docker.internal